// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjectManager_WebApi.Data;

namespace ProjectManager_WebApi.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20201105034823_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9");

            modelBuilder.Entity("ProjectManager_WebApi.Models.Programador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProjetoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Telefone")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjetoId");

                    b.ToTable("Programadores");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Lucas",
                            ProjetoId = 4,
                            Telefone = "61996253833"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Vivian",
                            ProjetoId = 4,
                            Telefone = "61999388883"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Vitor",
                            ProjetoId = 2,
                            Telefone = "61948546512"
                        },
                        new
                        {
                            Id = 4,
                            Nome = "Guilherme",
                            ProjetoId = 1,
                            Telefone = "61945123484"
                        },
                        new
                        {
                            Id = 5,
                            Nome = "Daniel",
                            ProjetoId = 4,
                            Telefone = "61978546218"
                        },
                        new
                        {
                            Id = 6,
                            Nome = "Marcia",
                            ProjetoId = 2,
                            Telefone = "61978543123"
                        },
                        new
                        {
                            Id = 7,
                            Nome = "Phelipe",
                            ProjetoId = 1,
                            Telefone = "61978543151"
                        },
                        new
                        {
                            Id = 8,
                            Nome = "Ana",
                            ProjetoId = 3,
                            Telefone = "61978541254"
                        },
                        new
                        {
                            Id = 9,
                            Nome = "Julia",
                            ProjetoId = 2,
                            Telefone = "61978545548"
                        });
                });

            modelBuilder.Entity("ProjectManager_WebApi.Models.Projeto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Prazo")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Projetos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Refatoração Autenticação",
                            Prazo = new DateTime(2020, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Aplicativo para restaurante",
                            Prazo = new DateTime(2020, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Painel de BI",
                            Prazo = new DateTime(2021, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            Nome = "ChatBot",
                            Prazo = new DateTime(2020, 11, 13, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("ProjectManager_WebApi.Models.Programador", b =>
                {
                    b.HasOne("ProjectManager_WebApi.Models.Projeto", "Projeto")
                        .WithMany("programadores")
                        .HasForeignKey("ProjetoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
